### ISSUE TITLE
Support for SAML2 login with Okta

### ISSUE THREAD

**Issue by AdigaAkhil** [ivangfr/springboot-react-social-login#11]
Could you please add SAML2 login to this project with Okta;

**Comment by ivangfr** [comment]
Hi @AdigaAkhil

In this project, we are focusing on social login in general. Currently, just **GitHub**.

Would [okta-springboot](https://github.com/ivangfr/okta-springboot) or [okta-springboot-react](https://github.com/ivangfr/okta-springboot-react) satisfy your needs?

Thanks.

**Comment by AdigaAkhil** [comment]
Yeah , I have seen that project . But in that you are doing OIDC login .

**Comment by AdigaAkhil** [comment]
Hello Ivangfr ,

I will close the issue , but I wanted to know if you will work on a project
which will deal with SAML login with any IDP . The way you have structured
the social login code is really good . So will you make the same for SAML2
login with okta as IDP.

**Comment by ivangfr** [comment]
It looks interesting. But, probably, I won't work on that during the coming months.

**Comment by AdigaAkhil** [comment]
Ohh ok then. I'll close this.
