### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by arya020** [ivangfr/springboot-react-social-login#12]
Consider defining a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' in your configuration.

**Comment by ivangfr** [comment]
Hi @arya020 Could you describe the issue you are having and why the `ClientRegistrationRepository` bean should be implemented? Thanks!

**Comment by arya020** [comment]
I have modified the code to use mongo as database.. I am not sure what might have gone wrong...


***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method setFilterChains in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' in your configuration.


Process finished with exit code 1

**Comment by ivangfr** [comment]
Ok, thanks! I believe the current version of the `springboot-react-social-login` project is working fine.
