### ISSUE TITLE
Database Connection Timeout with PostgreSQL on Springboot Application

### ISSUE THREAD

**Issue by Lewi217** [ivangfr/springboot-react-social-login#14]
When attempting to connect to a PostgreSQL database from our SpringBoot application, I encounter connection timeouts. The issue seems to occur more frequently during the peak usage times.

**Comment by ivangfr** [comment]
Hi @Lewi217 The issue occurs while using this project. More information is needed (Java and Spring Boot versions, OS, screenshots, logs, etc.).
